### ISSUE TITLE
hwcomposer

### ISSUE THREAD

**Issue by microzans** [remilia15/android_hardware_sprd#13]
`target thumb C++: hwcomposer.sc8830 <= hardware/sprd/hwcomposer/sc8830/SprdHWComposer.cpp target thumb C++: hwcomposer.sc8830 <= hardware/sprd/hwcomposer/sc8830/SprdPrimaryDisplayDevice/SprdFrameBufferHAL.cpp In file included from hardware/sprd/hwcomposer/sc8830/SprdPrimaryDisplayDevice/../OverlayComposer/OverlayNativeWindow.h:36:0, from hardware/sprd/hwcomposer/sc8830/SprdPrimaryDisplayDevice/../OverlayComposer/OverlayComposer.h:91, from hardware/sprd/hwcomposer/sc8830/SprdPrimaryDisplayDevice/SprdPrimaryDisplayDevice.h:61, from hardware/sprd/hwcomposer/sc8830/SprdHWComposer.h:53, from hardware/sprd/hwcomposer/sc8830/SprdHWComposer.cpp:37: frameworks/native/include/ui/FramebufferNativeWindow.h:18:2: warning: #warning "FramebufferNativeWindow is deprecated" [-Wcpp] #warning "FramebufferNativeWindow is deprecated" ^ target thumb C++: hwcomposer.sc8830 <= hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp In file included from hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:40:0: system/core/libion/include/ion/ion.h:34:35: error: 'ion_user_handle_t' has not been declared unsigned int flags, ion_user_handle_t *handle); ^ system/core/libion/include/ion/ion.h:38:22: error: 'ion_user_handle_t' has not been declared int ion_free(int fd, ion_user_handle_t handle); ^ system/core/libion/include/ion/ion.h:39:21: error: 'ion_user_handle_t' has not been declared int ion_map(int fd, ion_user_handle_t handle, size_t length, int prot, ^ system/core/libion/include/ion/ion.h:41:23: error: 'ion_user_handle_t' has not been declared int ion_share(int fd, ion_user_handle_t handle, int *share_fd); ^ system/core/libion/include/ion/ion.h:42:38: error: 'ion_user_handle_t' has not been declared int ion_import(int fd, int share_fd, ion_user_handle_t *handle); ^ target thumb C++: hwcomposer.sc8830 <= hardware/sprd/hwcomposer/sc8830/SprdDisplayPlane.cpp hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:63:27: error: use of enum 'SPRD_DEVICE_SYNC_TYPE' without previous declaration int sprd_fence_build(enum SPRD_DEVICE_SYNC_TYPE type, struct HWC_fence_data *HWCData) ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp: In function 'int sprd_fence_build(int, HWC_fence_data*)': hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:81:10: error: 'struct ion_fence_data' has no member named 'device_type' data.device_type = type; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:82:10: error: 'struct ion_fence_data' has no member named 'life_value' data.life_value = 1; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:83:10: error: 'struct ion_fence_data' has no member named 'release_fence_fd' data.release_fence_fd = -1; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:84:10: error: 'struct ion_fence_data' has no member named 'retired_fence_fd' data.retired_fence_fd = -1; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:96:14: error: 'struct ion_fence_data' has no member named 'release_fence_fd' if (data.release_fence_fd < 0 || data.retired_fence_fd < 0) ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:96:43: error: 'struct ion_fence_data' has no member named 'retired_fence_fd' if (data.release_fence_fd < 0 || data.retired_fence_fd < 0) ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:102:38: error: 'struct ion_fence_data' has no member named 'release_fence_fd' HWCData->release_fence_fd = data.release_fence_fd; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:103:38: error: 'struct ion_fence_data' has no member named 'retired_fence_fd' HWCData->retired_fence_fd = data.retired_fence_fd; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp: At global scope: hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:108:28: error: use of enum 'SPRD_DEVICE_SYNC_TYPE' without previous declaration int sprd_fence_signal(enum SPRD_DEVICE_SYNC_TYPE type) ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp: In function 'int sprd_fence_signal(int)': hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:121:10: error: 'struct ion_fence_data' has no member named 'device_type' data.device_type = type; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp: In function 'int HWCBufferSyncBuild(hwc_display_contents_1_t*, int)': hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:241:10: error: use of enum 'SPRD_DEVICE_SYNC_TYPE' without previous declaration enum SPRD_DEVICE_SYNC_TYPE device_type = SPRD_DEVICE_PRIMARY_SYNC; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:241:44: error: invalid type in declaration before '=' token enum SPRD_DEVICE_SYNC_TYPE device_type = SPRD_DEVICE_PRIMARY_SYNC; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:241:46: error: 'SPRD_DEVICE_PRIMARY_SYNC' was not declared in this scope enum SPRD_DEVICE_SYNC_TYPE device_type = SPRD_DEVICE_PRIMARY_SYNC; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:246:23: error: 'SPRD_DEVICE_VIRTUAL_SYNC' was not declared in this scope device_type = SPRD_DEVICE_VIRTUAL_SYNC; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp: In function 'int HWCBufferSyncBuildForVirtualDisplay(hwc_display_contents_1_t*)': hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:319:10: error: use of enum 'SPRD_DEVICE_SYNC_TYPE' without previous declaration enum SPRD_DEVICE_SYNC_TYPE device_type; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:319:43: error: invalid type in declaration before ';' token enum SPRD_DEVICE_SYNC_TYPE device_type; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:322:19: error: 'SPRD_DEVICE_VIRTUAL_SYNC' was not declared in this scope device_type = SPRD_DEVICE_VIRTUAL_SYNC; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp: In function 'int HWCBufferSyncReleaseForVirtualDisplay(hwc_display_contents_1_t*)': hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:374:10: error: use of enum 'SPRD_DEVICE_SYNC_TYPE' without previous declaration enum SPRD_DEVICE_SYNC_TYPE device_type = SPRD_DEVICE_VIRTUAL_SYNC; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:374:44: error: invalid type in declaration before '=' token enum SPRD_DEVICE_SYNC_TYPE device_type = SPRD_DEVICE_VIRTUAL_SYNC; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:374:46: error: 'SPRD_DEVICE_VIRTUAL_SYNC' was not declared in this scope enum SPRD_DEVICE_SYNC_TYPE device_type = SPRD_DEVICE_VIRTUAL_SYNC; ^ hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp: At global scope: hardware/sprd/hwcomposer/sc8830/AndroidFence.cpp:364:69: warning: unused parameter 'list' [-Wunused-parameter] int HWCBufferSyncReleaseForVirtualDisplay(hwc_display_contents_1_t *list)`

**Comment by microzans** [comment]
I did not compile the whole project, but only the library
make hwcomposer.sc8830

**Comment by tim241** [comment]
I'm having the exact same error, my device tree: https://github.com/tim241/android_device_samsung_kanas3gnfcxx/tree/cm-13.0

**Comment by muralivijay** [comment]
iam also getting this erros in omx and hwcomposer sc9830

**Comment by chaubeyprateek** [comment]
Fix it

**Comment by remilia15** [comment]
Fixed 69 years ago

**Comment by batmanlovesuperman** [comment]
@remilia15 lol

**Comment by chaubeyprateek** [comment]
@batmanlovesuperman wtf gays

**Comment by batmanlovesuperman** [comment]
@chaubeyprateek wtf?

**Comment by remilia15** [comment]
He's pure gay

**Comment by batmanlovesuperman** [comment]
@remilia15 no fuck you

**Comment by remilia15** [comment]
Stop trash comments and go tg

**Comment by batmanlovesuperman** [comment]
@remilia15 okay

**Comment by chaubeyprateek** [comment]
@batmanlovesuperman K bruh k

**Comment by chaubeyprateek** [comment]
@remilia15 Nu plod
